version: "3.9"
volumes:
  postgres-db:
  saved-datesets:
services:
  postgres:
    image: postgres:16
    volumes:
    - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-Time_series}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    ports:
      - "5432:5432"
  flaskapplication:
    container_name: time_series_analyser
    image: sanderbos/time_series_analyser:0.0.1
    ports:
    - "8000:8000"
    volumes:
    - saved-datesets:/data
    environment:
      SECRET_KEY: ${SECRET_KEY}:-12345
    depends_on:
      postgres:
        condition: service_started